[package]
name = "parser"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib"]
name = "parser_rust"

[dependencies]
log = { version = "0.4" }
parser_lib = { path = "../parser_lib" }

[dependencies.pyo3]
version = "0.15.2"
features = ["abi3-py36", "auto-initialize", "extension-module"]

