[package]
name = "parser"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib"]
name = "parser_rust"

[dependencies]
ipnet = "2.11.0"
log = { version = "0.4" }
macros = { path = "../macros" }
nom = "8.0.0"
serde = "1.0.219"
serde_derive = "1.0.219"
smol_str = { version = "0.3.6", features = ["serde"] }
yaml_serde = "0.10"

[dependencies.pyo3]
version = "0.15.2"
features = ["abi3-py36", "auto-initialize", "extension-module"]

[dev-dependencies]
diff = { path = "../diff" }
fixtures = "2.5.0"
tester = { path = "../tester" }

[build-dependencies]
fixtures = "2.5.0"
